# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftLogin
   pod 'RxSwift'
   pod 'RxCocoa'
  target 'RxSwiftLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftLoginUITests' do
    # Pods for testing
  end

end
